export const ACTION_TICK_TIMER = 'ACTION_TICK_TIMER';
export const ACTION_START_TIMER = 'ACTION_START_TIMER';
export const ACTION_PAUSE_TIMER = 'ACTION_PAUSE_TIMER';
export const ACTION_STOP_TIMER = 'ACTION_STOP_TIMER';
export const ACTION_NEXT_TIMER = 'ACTION_NEXT_TIMER';

export const ACTION_SHOW_SETTINGS = 'ACTION_SHOW_SETTINGS';
